Acart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

                  path('', include('ecommerce.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')), #read django authentication views
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from .views import *

app_name = 'ecommerce'  # namespace

urlpatterns = [
    path('', Homepage.as_view(), name='index'),
    path('register', SignUpView.as_view(), name='register'),
    path('category/<str:category_slug>', CategoryWise.as_view(), name='category_wise'),
    path('product/<str:product_slug>', ProductView.as_view(), name='single_product'),
    path('search/', SearchView.as_view(), name='search'),
    path('api/categories', CategoryApiView.as_view()),
    path('cart', CartView.as_view(), name='cart'),
    path('demo/<int:id>', demoGlass.as_view(), name='demoGlass'),
    path('remove/<int:id>', remove_product, name='remove_product'),
    path('contactus', ContactUsView.as_view(), name='ContactUs'),
    path('orderplacement', OrderPlacementView.as_view(), name='Order_placement')

]

templates/partials/base_search.html
<form action="{% url 'ecommerce:search' %}">
    <div class="row"><center><h2>Welcome to Rayban house,Goggles Zone</h2></center></div>
    <div class="row">
        <div class="col-md-9"> <input type="text" name="q" placeholder="Search products..." required> </div>
        <div class="col-md-3"> <input type="submit" value="Search"> </div>
    </div>
</form>

templates/partials/search.html
<form action="{% url 'ecommerce:search' %}">
    <input type="text" name="q" placeholder="Search products..." required>
    <input type="submit" value="Search">
</form>