Acart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

                  path('', include('ecommerce.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')), #read django authentication views
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from .views import *

app_name = 'ecommerce'  # namespace

urlpatterns = [
    path('', Homepage.as_view(), name='index'),
    path('register', SignUpView.as_view(), name='register'),
    path('category/<str:category_slug>', CategoryWise.as_view(), name='category_wise'),
    path('product/<str:product_slug>', ProductView.as_view(), name='single_product'),
    path('search/', SearchView.as_view(), name='search'),
    path('api/categories', CategoryApiView.as_view()),
    path('cart', CartView.as_view(), name='cart'),
    path('demo/<int:id>', demoGlass.as_view(), name='demoGlass'),
    path('remove/<int:id>', remove_product, name='remove_product'),
    path('contactus', ContactUsView.as_view(), name='ContactUs'),
    path('orderplacement', OrderPlacementView.as_view(), name='Order_placement')

]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>

    <!-- INCLUDE MAIN SCRIPT -->
    {% block head %}
    {% endblock %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rayban house,Goggles Zone</title>
    <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'/>
    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet'
          type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="header-area">

    <div class="row">
        <center>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success">
                        <strong>{{ message }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        </center>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="user-menu">
                    <ul>

                        {% if request.user.is_authenticated %}
                            <li><a href="#"><i class="fa fa-user"></i> {{ request.user }}</a></li>
                            <li><a href="{% url 'ecommerce:cart' %}"><i class="fa fa-user"></i> My Cart</a>
                            </li>


                            <li><a href="{% url 'logout' %}"><i class="fa fa-user"></i> Logout</a></li>
                            {# here url 'logout' is from#}
                            {# django.contrib.auth.urls that we have included in main urls. check django views authentication documentation #}
                        {% else %}
                            <li><a href="{% url 'ecommerce:register' %}"><i class="fa fa-user"></i> Signup</a></li>
                            {# since we don't have any methods or urls for signup in django.contrib.auth.urls, we created our own method and urls#}
                            <li><a href="{% url 'login' %}"><i class="fa fa-user"></i> Login</a></li>
                            {# django.contrib.auth.urls that we have included in main urls. #}
                        {% endif %}

                    </ul>
                </div>
            </div>


        </div>
    </div>
</div> <!-- End header area -->

<div class="site-branding-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="logo">
                    <h1><a href="/"><img src="{% static 'img/logo.png' %}"></a></h1>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="single-sidebar">
                    {% include 'partials/base_search.html' %}
                </div>
            </div>
            <div class="col-sm-3">
                <div class="shopping-item">
                    <a href="{% url 'ecommerce:cart' %}">Cart <span class="cart-amunt"></span> <i
                            class="fa fa-shopping-cart"></i></a>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End site branding area -->

<div class="mainmenu-area">
    <div class="container">
        <div class="row">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li {% if request.path == '/' %}class="active" {% endif %}><a href="/">Home</a></li>
                    {# we need to give url / for home alway not blank space or nothing #}
                    {# here we are including home even though we don't have home category, therefore outside of our category loop #}
                    {# here we give / in href to make home page clickable#}
                    {% for a_category in categories %}
                        {# loop ma vako category ra context bata aako category judxa tei vayere, a_category banako #}
                        <li{% if  '/category/' in request.path and a_category == category %}
                            class="active" {% endif %}><a
                                href="{% url 'ecommerce:category_wise' a_category.slug %}">{{ a_category.title }}</a>{# remember always from our model class slug and title #}
                        </li>
                    {% endfor %}
                    <li><a href="{% url 'ecommerce:ContactUs' %}">Contact Us</a></li>


                    {% for a_page in navbar_pages %}{# this is for about us contact us #}

                        <li {% if  '/cms/pages/' in request.path and a_page == page %}
                            class="active" {% endif %}><a
                                href="{% url 'cms:page' a_page.slug %}">{{ a_page.menu_title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div> <!-- End mainmenu area -->


{% block content %}
{% endblock %}

<div class="footer-top-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="footer-about-us">
                    <h2>Rayban house,<span>Goggles Zone </span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam
                        laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure
                        eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis
                        magni at?</p>
                    <div class="footer-social">
                        <a href="" target="_blank"><i class="fa fa-facebook"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-menu">
                    <h2 class="footer-wid-title">User Navigation </h2>
                    <ul>
                        <li><a href="{% url 'ecommerce:cart' %}">Cart</a></li>

                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-menu">
                    <h2 class="footer-wid-title">Categories</h2>
                    <ul>
                        {% for a_category in categories %}
                            <li><a href="#">{{ a_category.title }}</a></li>
                        {% endfor %}

                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-newsletter">
                    <h2 class="footer-wid-title">Newsletter</h2>
                    <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your
                        inbox!</p>
                    <div class="newsletter-form">
                        <form action="#">
                            <input type="email" placeholder="Type your email">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End footer top area -->

<div class="footer-bottom-area">
    <div class="container">
        <div class="row">
            <center>
                <div class="copyright">
                    <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="http://www.freshdesignweb.com"
                                                                      target="_blank">freshDesignweb.com</a></p>
                </div>
            </center>

            <div class="footer-card-icon">
                <i class="fa fa-cc-discover"></i>
                <i class="fa fa-cc-mastercard"></i>
                <i class="fa fa-cc-paypal"></i>
                <i class="fa fa-cc-visa"></i>
            </div>
        </div>
    </div>
</div> <!-- End footer bottom area -->

<!-- Latest jQuery form server -->
<script src="https://code.jquery.com/jquery.min.js"></script>

<!-- Bootstrap JS form CDN -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<!-- jQuery sticky menu -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>

<!-- jQuery easing -->
<script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/main.js' %}"></script>

<!-- Slider -->
<script type="text/javascript" src="{% static 'js/bxslider.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script.slider.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}

    <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Shopping Cart</h2>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Page title area -->


    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="single-sidebar">
                        <h2 class="sidebar-title">Search Products</h2>
                        {% include 'partials/search.html' %}
                    </div>

                    <div class="single-sidebar">
                        <h2 class="sidebar-title">Products</h2>
                        {% for a_product in latest_products %}
                            <div class="thubmnail-recent">

                                {% thumbnail a_product.image.image "190x190" crop="center" as im %}
                                    <img src="{{ im.url }}" class="recent-thumb">
                                {% endthumbnail %}
                                <h2>
                                    <a href="{% url 'ecommerce:single_product' a_product.slug %}">{{ a_product.title }}</a>
                                </h2>
                                <div class="product-sidebar-price">
                                    <ins>${{ a_product.price }}</ins>
                                </div>
                            </div>
                        {% endfor %}
                    </div>


                </div>

                <div class="col-md-8">
                    <div class="product-content-right">
                        <div class="woocommerce">
                            <form method="post" action="#">
                                <table cellspacing="0" class="shop_table cart">
                                    <thead>
                                    <tr>
                                        <th class="product-remove">&nbsp;</th>
                                        <th class="product-thumbnail">&nbsp;</th>
                                        <th class="product-name">Product</th>
                                        <th class="product-price">Price</th>
                                        <th class="product-quantity">Quantity</th>
                                        <th class="product-subtotal">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for cart_item in cart_items %}
                                        <tr class="cart_item">
                                            <td class="product-remove">
                                                <a title="Remove this item" class="remove" href="{% url 'ecommerce:remove_product' cart_item.id %}">×</a>
                                            </td>

                                            <td class="product-thumbnail">
                                                <a href="{% url 'ecommerce:single_product' cart_item.product.slug %}">
                                                    {% thumbnail cart_item.product.image.image "100x100" crop="center" as im %}
                                                        <img src="{{ im.url }}" width="145" height="145"
                                                             alt="poster_1_up" class="shop_thumbnail">
                                                    {% endthumbnail %}</a>

                                            </td>
                                            <td class="product-name">
                                                <a href="{% url 'ecommerce:single_product' cart_item.product.slug %}">{{ cart_item.product.title }}</a>
                                            </td>

                                            <td class="product-price">
                                                <span class="amount">{{ cart_item.product.price }}</span>
                                            </td>

                                            <td class="product-quantity">
                                                <div class="quantity buttons_added">
                                                    {{ cart_item.qty }}

                                                </div>
                                            </td>

                                            <td class="product-subtotal">
                                                <span class="amount">{{ cart_item.total }}</span>
                                                {# here total is function in cart model #}
                                            </td>
                                        </tr>
                                        <tr>

                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </form>

                            <div class="cart-collaterals">


                                <div class="cross-sells">
                                    <h2>You may be interested in...</h2>
                                    <ul class="products">
                                        {% for a_product in intrested_products %}
                                            <li class="product">
                                                <a href="{% url 'ecommerce:single_product' a_product.slug %}">
                                                    {% thumbnail a_product.image.image "195x243" crop="center" as im %}
                                                        <img src="{{ im.url }}" width="325"
                                                             height="325" class="attachment-shop_catalog wp-post-image">
                                                    {% endthumbnail %}

                                                    <h3>{{ a_product.title }}</h3>
                                                    <span class="price"><span
                                                            class="amount">Rs. {{ a_product.price }}</span></span>
                                                </a>

                                                <a class="add_to_cart_button" data-quantity="1" data-product_sku=""
                                                   data-product_id="22" rel="nofollow" href="{% url 'ecommerce:single_product' a_product.slug  %}">See Datails</a>
                                            </li>
                                        {% endfor %}

                                    </ul>
                                </div>


                                <div class="cart_totals ">
                                    <h2>Cart Totals</h2>

                                    <table cellspacing="0">
                                        <tbody>
                                        <tr class="cart-subtotal">
                                            <th>Cart Subtotal</th>
                                            <td><span class="amount">Rs. {{ total_amount }}</span></td>
                                        </tr>

                                        <tr class="shipping">
                                            <th>Shipping and Handling</th>
                                            <td>Free Shipping</td>
                                        </tr>

                                        <tr class="order-total">
                                            <th>Order Total</th>
                                            <td><strong><span class="amount">{{ total_amount }}</span></strong></td>
                                        </tr>
                                        <tr>
                                            <th>Confirm here -></th>
                                            <td>
                                                <a href="{% url 'ecommerce:Order_placement' %}">Confirm Products</a>
                                            </td>
                                        </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load app_filters %} {# don't forget to load #}
{% block content %}
    <div class="slider-area">
        <!-- Slider -->
        <div class="block-slider block-slider4">
            <ul class="" id="bxslider-home4">
                {% for banner in banners %}
                    <li>
                        {% thumbnail banner.image "1163x365" crop="center" as im %}
                            <img src="{{ im.url }}">{# no need to specify image url ourself when using sorl thumbnail #}
                        {% endthumbnail %}
                        <div class="caption-group">
                            <h2 class="caption title">
                                {{ banner.caption }}
                            </h2>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <!-- ./Slider -->
    </div> <!-- End slider area -->

    <div class="promo-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo1">
                        <i class="fa fa-refresh"></i>
                        <p>30 Days return</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo2">
                        <i class="fa fa-truck"></i>
                        <p>Free shipping</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo3">
                        <i class="fa fa-lock"></i>
                        <p>Secure payments</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo4">
                        <i class="fa fa-gift"></i>
                        <p>New products</p>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End promo area -->

    <div class="maincontent-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="latest-product">
                        <h2 class="section-title">Latest Products</h2>
                        <div class="product-carousel">
                            {% for product in latest_products %}
                                <div class="single-product float">
                                    <div class="product-f-image">
                                        {% thumbnail product.image.image "195x243" crop="center" as im %}
                                            <img src="{{ im.url }}" style="width: 100%">
                                        {% endthumbnail %}
                                        <div class="product-hover">
{#                                            <a href="{% url 'ecommerce:cart' %}" class="add-to-cart-link"><i#}
{#                                                    class="fa fa-shopping-cart"></i> Add#}
{#                                                to#}
{#                                                cart</a>#}
                                            <a href="{% url 'ecommerce:single_product' product.slug %}"
                                               class="view-details-link"><i
                                                    class="fa fa-link"></i> See details</a>
                                        </div>
                                    </div>
                                    <div>
                                        <a href="{% url 'ecommerce:demoGlass' product.id%}"><i
                                        ></i> Try this Product</a>
                                    </div>
                                    <h2>
                                        <a href="{% url 'ecommerce:single_product' product.slug %}">{{ product.title }}</a>
                                    </h2>

                                    <div class="product-carousel-price">
                                        <ins>Rs. {{ product.price }}</ins>
                                        <del>Rs. {{ product.discount }}</del>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End main content area -->

    <div class="brands-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="brand-wrapper">
                        <h2 class="section-title"><p style="color: grey;">Our Brands</h2>
                        <div class="brand-list">
                            {% for brand in brands %}
                                <div style="height: 150px">
                                <img src="{{ brand.image.url }}" alt="" >{# check this out #}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End brands area -->

    <div class="product-widget-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="single-product-widget">
                        <h2 class="product-wid-title">Top Sellers</h2>

                        {% for product in top_sellers %}
                            <div class="single-wid-product">
                                <a href="{% url 'ecommerce:single_product' product.slug %}">
                                    {% thumbnail product.image.image "100x90" crop="center" as im %}
                                        <img src="{{ im.url }}" class="product-thumb">
                                    {% endthumbnail %}
                                </a>
                                <h2><a href="{% url 'ecommerce:single_product' product.slug %}">{{ product.title }}</a>
                                </h2>
                                <div class="product-wid-rating">

                                    {% for i in product.avg_rating|range %}{# no space while using pipe #}
                                        <i class="fa fa-star"></i>
                                    {% endfor %}
                                </div>
                                <div class="product-wid-price">
                                    <ins>Rs. {{ product.price }}</ins>
                                    <del>Rs. {{ product.discount }}</del>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="single-product-widget">
                        <h2 class="product-wid-title">Recently Viewed</h2>
                        {% for product in recently_viewed %}
                            <div class="single-wid-product">
                                <a href="{% url 'ecommerce:single_product' product.slug %}">
                                    {% thumbnail product.image.image "100x90" crop="center" as im %}
                                        <img src="{{ im.url }}" class="product-thumb">
                                    {% endthumbnail %}
                                </a>
                                <h2><a href="{% url 'ecommerce:single_product' product.slug %}">{{ product.title }}</a>
                                </h2>
                                <div class="product-wid-rating">
                                    {% for i in product.avg_rating|range %}{# no space while using pipe #}
                                        <i class="fa fa-star"></i>
                                    {% endfor %}
                                </div>
                                <div class="product-wid-price">
                                    <ins>Rs. {{ product.price }}</ins>
                                    <del>Rs. {{ product.discount }}</del>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="single-product-widget">
                        <h2 class="product-wid-title">Top New</h2>
                        {% for product in top_new_products %}
                            <div class="single-wid-product">
                                <a href="{% url 'ecommerce:single_product' product.slug %}">
                                    {% thumbnail product.image.image "100x90" crop="center" as im %}
                                        <img src="{{ im.url }}" class="product-thumb">
                                    {% endthumbnail %}
                                </a>
                                <h2><a href="{% url 'ecommerce:single_product' product.slug %}">{{ product.title }}</a>
                                </h2>
                                <div class="product-wid-rating">
                                    {% for i in product.avg_rating|range %}{# no space while using pipe #}
                                        <i class="fa fa-star"></i>
                                    {% endfor %}
                                </div>
                                <div class="product-wid-price">
                                    <ins>Rs. {{ product.price }}</ins>
                                    <del>Rs. {{ product.discount }}</del>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End product widget area -->


{% endblock %}